### ISSUE TITLE
Installation of stuff in requirements.txt

### ISSUE THREAD

**Issue by Runefeather** [robin-lee/store#1]
(For ubuntu)
While installing **psycopg2==2.6.2** as per requirements.txt (```pip install requirements.txt```), you might get an error like this:   
```Error: pg_config executable not found```    
This is solvable by running:   
```sudo apt install libpq-dev python3-dev``` (python3, and ubuntu 16.04. If you are using 14.04, use apt-get)
then when you do *pip install*, it works fine.

**Comment by robin-lee** [comment]
Thanks.
